ALTER TABLE "Defect"
  ADD COLUMN IF NOT EXISTS "reminderCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lastRemindedAt" TIMESTAMP(3);

ALTER TABLE "DefectHistory"
  ADD COLUMN IF NOT EXISTS "reminderCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lastRemindedAt" TIMESTAMP(3);
