"use client";
import { useEffect, useId, useState } from "react";
import { useSession } from "next-auth/react";
import { ClipboardList, Download, Plus, Search, Wrench, Zap, ArrowRight, Clock, RefreshCw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { ContractorSessions, PermitMembersEditor, PermitPeopleDirectory } from "@/components/work-permits/contractor-work";
import { PermitSafetyCatalog, PermitSafetySelection, PermitSafetyReadOnly } from "@/components/work-permits/safety";
import { useExportPermitTemplate } from "@/hooks/useWorkPermitSafety";
import { PermitExecutionDialog } from "@/components/work-permits/execution";
import { PermitHistoryPanel } from "@/components/work-permits/history";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { useWorkPermits, useWorkPermit, useSaveWorkPermit, useExportWorkPermits, usePermitNumberSuggestion } from "@/hooks/useWorkPermits";
import { useUsers } from "@/hooks/useUsers";
import { useDefects, type DefectItem } from "@/hooks/useDefects";
import { announcementPositionsMatch, OPERATION_POSITION_TITLES } from "@/lib/positions";
import { formatPermitNumber, PERMIT_DISCIPLINES, type PermitDiscipline, PERMIT_PAGE_SIZE, PERMIT_FORMATS, defaultPermitFormat, effectivePermitFormat, type PermitFormatValue, PERMIT_KINDS, PERMIT_WORK_TYPES, PERMIT_WORK_TYPE_CODES, PERMIT_STATUSES, PERMIT_UNITS, PERMIT_TRANSITIONS, CONTRACTOR_PERMIT_TRANSITIONS, PERMIT_FIELD_LABELS, permitValue, type PermitWorkType, type PermitInput, type PermitKind, type PermitRow, type PermitStatus } from "@/lib/work-permits";

const control = "min-h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring disabled:opacity-60";
const filterControl = "min-h-9 w-full rounded-md border border-input bg-background px-2.5 py-1.5 text-xs text-foreground focus:outline-none focus:ring-2 focus:ring-ring disabled:opacity-60";
const statusColors: Record<PermitStatus, string> = { DRAFT: "bg-muted text-muted-foreground", ISSUED: "bg-sky-100 text-sky-800", ACTIVE: "bg-emerald-100 text-emerald-800", PAUSED: "bg-amber-100 text-amber-900", WAITING: "bg-amber-100 text-amber-900", CLOSED: "bg-slate-200 text-slate-700", CANCELLED: "bg-red-100 text-red-800" };
function Status({ value }: { value: PermitStatus }) { return <span className={`inline-flex whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-semibold ${statusColors[value]}`}>{PERMIT_STATUSES[value]}</span>; }
function PermitProgress({ value }: { value: number | null | undefined }) { return value == null ? null : <p className="mt-1 whitespace-nowrap text-xs font-semibold tabular-nums text-blue-700">Tiến độ {value}%</p>; }
function PermitFormat({ permit }: { permit: Pick<PermitInput, "format" | "teamType"> }) {
  const paper = effectivePermitFormat(permit) === "PAPER";
  return <span title={paper ? "Cấp theo hình thức phiếu giấy" : "Cấp theo hình thức phiếu điện tử"} className={`inline-flex rounded-md px-2 py-0.5 text-xs font-medium ${paper ? "bg-amber-50 text-amber-800 dark:bg-amber-950/40 dark:text-amber-200" : "bg-sky-50 text-sky-800 dark:bg-sky-950/40 dark:text-sky-200"}`}>{paper ? "PCT giấy" : "PCT điện tử"}</span>;
}
function vietnamNow() { return new Date(Date.now() + 7 * 3600000).toISOString().slice(0, 16); }
function localTime(value: string | null) { return value ? new Date(new Date(value).getTime() + 7 * 3600000).toISOString().slice(0, 16) : ""; }
function defaultForm(kind: PermitKind): PermitInput {
  return { registrationNumber: "", workScope: "", plannedStartAt: null, plannedEndAt: null, disciplines: [], safetyItems: [], kind, format: "PAPER", workType: null, members: [], year: Number(vietnamNow().slice(0, 4)), number: "", position: "", unit: "S1", content: "", location: "", workDate: vietnamNow().slice(0, 10), issuerName: "", electricalSafetySupervisorName: "", leaderName: "", commanderName: "", teamName: "", teamType: "CONTRACTOR", workerCount: null, authorizerName: "", issuedAt: null, authorizedAt: null, closedAt: null, result: "", note: "", statusReason: "", repairRequestNumber: "" };
}
export default function WorkPermitsPage() {
  const [safetyTab, setSafetyTab] = useState(false);
  const [kind, setKind] = useState<PermitKind>("MECHANICAL");
  const [q, setQ] = useState(""); const [search, setSearch] = useState("");
  const [workType, setWorkType] = useState("");
  const [teamType, setTeamType] = useState(""); const [status, setStatus] = useState(""); const [unit, setUnit] = useState(""); const [position, setPosition] = useState("");
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1);
  const [editor, setEditor] = useState<PermitRow | "new" | null>(null);
  const [directory, setDirectory] = useState(false);
  const [exportOpen, setExportOpen] = useState(false);
  const [exportMode, setExportMode] = useState<"year" | "filters">("year");
  const [exportYear, setExportYear] = useState(Number(vietnamNow().slice(0, 4)));
  const [detail, setDetail] = useState<string>();
  useEffect(() => { const timer = setTimeout(() => { setSearch(q); setPage(1); }, 300); return () => clearTimeout(timer); }, [q]);
  const filters = new URLSearchParams({ kind, q: search, status, unit, position, teamType, workType, from, to, page: String(page) }).toString();
  const query = useWorkPermits(filters, !safetyTab); const exporting = useExportWorkPermits();
  const rows = query.data?.data ?? []; const meta = query.data?.meta;
  const counts = meta?.counts ?? {};
  const openCount = (counts.DRAFT ?? 0) + (counts.ISSUED ?? 0) + (counts.ACTIVE ?? 0) + (counts.PAUSED ?? 0) + (counts.WAITING ?? 0);
  async function exportBook() {
    try {
      if (exportMode === "year" && (!Number.isInteger(exportYear) || exportYear < 2000 || exportYear > 2100)) { toast.error("Nhập năm cấp số từ 2000 đến 2100"); return; }
      const exportFilters = exportMode === "year" ? new URLSearchParams({ kind, year: String(exportYear) }).toString() : filters;
      const file = await exporting.mutateAsync(exportFilters); const url = URL.createObjectURL(file.blob); const a = document.createElement("a"); a.href = url; a.download = file.filename; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
    catch (e) { toast.error(e instanceof Error ? e.message : "Không thể xuất sổ"); }
  }
  return <div className="mx-auto max-w-[1600px] space-y-5 pb-8">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-border pb-5">
      <div className="flex gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-navy text-white"><ClipboardList /></div><div><p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Phân xưởng Vận hành 1</p><h1 className="mt-1 text-2xl font-bold text-foreground">Sổ cấp phiếu công tác</h1><p className="mt-1 text-sm text-muted-foreground">Ghi cấp phiếu · Theo dõi thực hiện · Bàn giao phiếu chưa đóng</p></div></div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setDirectory(true)}>Nhân sự nhà thầu</Button><Button variant="outline" onClick={() => setExportOpen(true)} disabled={safetyTab || !meta || exporting.isPending || query.isError}><Download />{exporting.isPending ? "Đang xuất…" : "Xuất Excel"}</Button>{!safetyTab && meta?.canIssue && <Button onClick={() => setEditor("new")}><Plus />Ghi cấp phiếu</Button>}</div>
    </header>
    <div className="flex flex-wrap gap-2" aria-label="Sổ PCT và biện pháp an toàn Cơ">{Object.entries(PERMIT_KINDS).map(([key, label]) => <div key={key} className="flex flex-wrap gap-1 rounded-xl border border-border p-1"><Button variant={kind === key && !safetyTab ? "default" : "ghost"} aria-pressed={kind === key && !safetyTab} onClick={() => { setKind(key as PermitKind); setSafetyTab(false); setPage(1); }}>{key === "MECHANICAL" ? <Wrench /> : <Zap />}PCT {label}</Button>{key === "MECHANICAL" && <Button variant={kind === key && safetyTab ? "default" : "ghost"} aria-pressed={kind === key && safetyTab} onClick={() => { setKind("MECHANICAL"); setSafetyTab(true); setPage(1); }}><ShieldCheck />Biện pháp an toàn Cơ</Button>}</div>)}</div>
    {safetyTab ? <PermitSafetyCatalog key={kind} kind={kind} /> : <>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[
      { title: "Phiếu chưa đóng", count: openCount, value: "OPEN", note: "Gồm nháp, đã cấp, đang làm và tạm dừng" },
      { title: "Đang thực hiện", count: counts.ACTIVE ?? 0, value: "ACTIVE", note: "Đã ghi nhận cho phép làm việc" },
      { title: "Nhà thầu chờ làm tiếp", count: counts.WAITING ?? 0, value: "WAITING", note: "Đã kết thúc lần làm việc, chưa đóng PCT" },
      { title: "Đã đóng", count: counts.CLOSED ?? 0, value: "CLOSED", note: "Đã ghi kết quả công việc" },
    ].map(card => <button key={card.value} onClick={() => { setStatus(status === card.value ? "" : card.value); setPage(1); }} aria-pressed={status === card.value} className={`rounded-lg border bg-card p-3 text-left transition-colors hover:border-sky-400 ${status === card.value ? "border-sky-500 ring-1 ring-sky-500" : "border-border"}`}><span className="flex items-center justify-between gap-2"><span className="text-xs font-medium text-muted-foreground">{card.title}</span><strong className="text-2xl leading-none tabular-nums text-foreground">{meta ? card.count : "—"}</strong></span><span className="mt-1.5 block text-[11px] leading-snug text-muted-foreground">{card.note}</span></button>)}</div>
    <section className="overflow-hidden rounded-xl border border-border bg-card">
      <div className="grid gap-2 border-b border-border p-3 sm:grid-cols-2 lg:grid-cols-6">
        <label className="text-[11px] font-medium text-muted-foreground lg:col-span-2">Tìm kiếm<div className="relative mt-1"><Search size={14} className="absolute left-2.5 top-2.5 text-muted-foreground" /><input className={`${filterControl} pl-8`} value={q} onChange={e => setQ(e.target.value)} placeholder="Số phiếu, ĐKCT, SYC, công việc, người…" maxLength={200} /></div></label>
        <label className="text-[11px] font-medium text-muted-foreground">Trạng thái<select className={`${filterControl} mt-1`} value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">Đang theo dõi (mặc định)</option><option value="OPEN">Phiếu chưa đóng</option>{Object.entries(PERMIT_STATUSES).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label>
        <label className="text-[11px] font-medium text-muted-foreground">Tổ máy<select className={`${filterControl} mt-1`} value={unit} onChange={e => { setUnit(e.target.value); setPage(1); }}><option value="">Tất cả tổ máy</option>{Object.entries(PERMIT_UNITS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label>
        <label className="text-[11px] font-medium text-muted-foreground">Cương vị<select className={`${filterControl} mt-1`} value={position} onChange={e => { setPosition(e.target.value); setPage(1); }}><option value="">Tất cả cương vị</option>{OPERATION_POSITION_TITLES.map(value => <option key={value} value={value}>{value}</option>)}</select></label>
        <label className="text-[11px] font-medium text-muted-foreground">KH / ĐX / SC<select className={`${filterControl} mt-1`} value={workType} onChange={e => { setWorkType(e.target.value); setPage(1); }}><option value="">Tất cả phân loại</option>{Object.entries(PERMIT_WORK_TYPES).map(([k, v]) => <option key={k} value={k}>{v}</option>)}<option value="UNCLASSIFIED">Chưa phân loại</option></select></label>
        <label className="text-[11px] font-medium text-muted-foreground">Loại đơn vị<select className={`${filterControl} mt-1`} value={teamType} onChange={e => { setTeamType(e.target.value); setPage(1); }}><option value="">Tất cả đơn vị</option><option value="INTERNAL">Nội bộ</option><option value="CONTRACTOR">Nhà thầu</option></select></label>
        <label className="text-[11px] font-medium text-muted-foreground">Từ ngày<input type="date" className={`${filterControl} mt-1`} value={from} onChange={e => { setFrom(e.target.value); setPage(1); }} /></label>
        <label className="text-[11px] font-medium text-muted-foreground">Đến ngày<input type="date" className={`${filterControl} mt-1`} value={to} min={from} onChange={e => { setTo(e.target.value); setPage(1); }} /></label>
      </div>
      <div className="flex flex-wrap items-center justify-between gap-2 px-3 py-2 text-[11px] text-muted-foreground"><span>Số liệu theo các điều kiện đã chọn.</span><Button size="sm" variant="ghost" className="h-7 px-2 text-xs" disabled={query.isFetching} onClick={() => query.refetch()}><RefreshCw size={14} />Tải lại</Button></div>
      {query.isError ? <div role="alert" className="p-8 text-center text-red-700">{query.error.message}</div> : query.isPending ? <p className="p-12 text-center text-muted-foreground" role="status">Đang tải sổ cấp phiếu…</p> : !rows.length ? <div className="p-12 text-center"><ClipboardList className="mx-auto mb-3 text-muted-foreground" size={32} /><h2 className="font-semibold">Chưa có phiếu phù hợp</h2><p className="mt-1 text-sm text-muted-foreground">Ghi cấp phiếu mới hoặc thay đổi bộ lọc để tra cứu.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-y border-border bg-muted/50 text-xs text-muted-foreground"><tr>{["KH/ĐX/SC", "Số PCT / ngày", "Nội dung công việc", "Người cấp", "Chỉ huy / đơn vị", "Người cho phép", "Trạng thái", ""].map((v, i) => <th key={i} className="px-4 py-3 font-semibold">{v}</th>)}</tr></thead><tbody>{rows.map(r => <tr key={r.id} className="border-b border-border last:border-0 hover:bg-muted/30"><td className="px-4 py-4"><span title={r.workType ? PERMIT_WORK_TYPES[r.workType] : "Chưa phân loại"} className={`inline-flex rounded-md px-2 py-1 text-xs font-bold ${r.workType === "INCIDENT" ? "bg-red-100 text-red-800" : r.workType === "UNPLANNED" ? "bg-amber-100 text-amber-900" : "bg-muted text-foreground"}`}>{r.workType ? PERMIT_WORK_TYPE_CODES[r.workType] : "—"}</span></td><td className="px-4 py-4"><button className="whitespace-nowrap text-[13px] font-bold text-blue-700 underline-offset-4 hover:underline" onClick={() => setDetail(r.id)}>{formatPermitNumber(r)}</button><div className="mt-1"><PermitFormat permit={r} /></div><div className="mt-1 text-xs text-muted-foreground">{permitValue("workDate", r.workDate)}</div></td><td className="max-w-sm px-4 py-4"><p className="line-clamp-2 font-medium">{r.content}</p><p className="mt-1 text-xs text-muted-foreground">{PERMIT_UNITS[r.unit]}{r.position ? ` · ${r.position}` : ""}{r.location ? ` · ${r.location}` : ""}</p>{r.repairRequestNumber && <p className="mt-1 text-xs text-blue-700">SYC {r.repairRequestNumber}</p>}</td><td className="px-4 py-4">{r.issuerName || "—"}</td><td className="px-4 py-4">{r.sessions?.[0]?.commanderName || r.commanderName || "—"}{r.teamType === "CONTRACTOR" && <span className="ml-1 rounded bg-amber-100 px-1.5 py-0.5 text-xs text-amber-900">Nhà thầu</span>}<p className="mt-1 text-xs text-muted-foreground">{r.sessions?.[0]?.company || r.teamName || "Chưa ghi đơn vị"}{r.workerCount ? ` · ${r.workerCount} người` : ""}</p></td><td className="px-4 py-4">{r.sessions?.[0]?.authorizerName || r.authorizerName || "—"}</td><td className="px-4 py-4"><Status value={r.status} /><PermitProgress value={r.progress} /></td><td className="px-4 py-4"><Button size="sm" variant="outline" onClick={() => setDetail(r.id)}>Xem phiếu<ArrowRight /></Button></td></tr>)}</tbody></table></div>}
      <footer className="flex items-center justify-between gap-3 border-t border-border p-4 text-sm"><span>{meta?.total ?? 0} phiếu · Trang {page}/{Math.max(1, Math.ceil((meta?.total ?? 0) / (meta?.pageSize ?? PERMIT_PAGE_SIZE)))}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page <= 1 || query.isFetching} onClick={() => setPage(page - 1)}>Trước</Button><Button variant="outline" size="sm" disabled={!meta || page * meta.pageSize >= meta.total || query.isFetching} onClick={() => setPage(page + 1)}>Sau</Button></div></footer>
    </section>
    <p className="text-xs text-muted-foreground">Sổ ghi nhận việc cấp và thực hiện PCT. Số phiếu nhập theo thực tế, không trùng trong cùng loại và năm; phiếu hủy vẫn giữ số.</p>
    </>}
    {exportOpen && <Dialog open onOpenChange={value => { if (!exporting.isPending) setExportOpen(value); }}><DialogContent><DialogTitle>Xuất Excel sổ cấp PCT</DialogTitle><DialogDescription>Sổ {PERMIT_KINDS[kind]}. File chỉ có một sheet Sổ cấp PCT.</DialogDescription>
      <label className="space-y-1 text-sm"><span>Phạm vi xuất</span><select className={control} value={exportMode} disabled={exporting.isPending} onChange={e => setExportMode(e.target.value as "year" | "filters")}><option value="year">Toàn bộ sổ theo năm cấp số</option><option value="filters">Theo bộ lọc đang xem</option></select></label>
      {exportMode === "year" ? <label className="space-y-1 text-sm"><span>Năm cấp số *</span><input className={control} type="number" min={2000} max={2100} disabled={exporting.isPending} value={exportYear || ""} onChange={e => setExportYear(Number(e.target.value))} /><p className="text-xs text-muted-foreground">Xuất tất cả phiếu của sổ đã chọn trong năm này, gồm giấy và điện tử. Không áp dụng bộ lọc ngày, trạng thái hoặc từ khóa bên ngoài.</p></label> : <p className="text-sm text-muted-foreground">Áp dụng các bộ lọc hiện tại, lấy toàn bộ trang kết quả.</p>}
      <Button disabled={exporting.isPending} onClick={exportBook}><Download />{exporting.isPending ? "Đang xuất…" : "Tải Excel"}</Button>
    </DialogContent></Dialog>}
    {directory && <PermitPeopleDirectory onClose={() => setDirectory(false)} />}
    {editor && <PermitEditor initial={editor === "new" ? undefined : editor} kind={kind} onClose={() => setEditor(null)} />}
    {detail && <PermitDetail key={detail} id={detail} canIssue={meta?.canIssue ?? false} canExecute={meta?.canExecute ?? false} onClose={() => setDetail(undefined)} onEdit={row => { setDetail(undefined); setEditor(row); }} />}
  </div>;
}

function PermitEditor({ initial, kind, onClose }: { initial?: PermitRow; kind: PermitKind; onClose: () => void }) {
  const [form, setForm] = useState<PermitInput>(initial ? { ...initial, format: effectivePermitFormat(initial), safetyItems: initial.kind === "ELECTRICAL" ? [] : initial.safetyItems } : defaultForm(kind));
  const [status, setStatus] = useState<PermitStatus>(initial?.status ?? "DRAFT");
  const [pickSyc, setPickSyc] = useState(false); const save = useSaveWorkPermit();
  const [pickCommander, setPickCommander] = useState(false);
  const { data: session } = useSession();
  const numberEditable = !initial || initial.status === "DRAFT";
  const numberSuggestion = usePermitNumberSuggestion(form.kind, form.year, numberEditable);
  const issuerDisplay = initial && initial.status !== "DRAFT" ? initial.issuerName : session?.user?.name ?? "";
  const users = useUsers({ enabled: form.teamType === "INTERNAL" }); const namesId = useId();
  const set = <K extends keyof PermitInput>(key: K, value: PermitInput[K]) => setForm(prev => ({ ...prev, [key]: value }));
  const textField = (key: keyof PermitInput, required = false, wide = false) => <label key={key} className={`space-y-1.5 text-sm ${wide ? "md:col-span-2" : ""}`}><span className="font-medium">{PERMIT_FIELD_LABELS[key]}{required ? " *" : ""}</span><input disabled={key === "authorizerName"} className={control} value={String(form[key] ?? "")} required={required} maxLength={key === "location" ? 500 : 200} list={key.endsWith("Name") && key !== "teamName" ? namesId : undefined} onChange={e => set(key, e.target.value as never)} /></label>;
  const dateField = (key: "issuedAt" | "authorizedAt" | "closedAt", required: boolean) => <label className="space-y-1.5 text-sm"><span className="font-medium">{PERMIT_FIELD_LABELS[key]} (giờ Việt Nam){required ? " *" : ""}</span><input disabled={key !== "issuedAt"} className={control} type="datetime-local" required={required} value={localTime(form[key])} onChange={e => set(key, e.target.value ? `${e.target.value}:00+07:00` : null)} /></label>;
  function changeFormat(format: PermitFormatValue, teamType = form.teamType) {
    if (format !== "PAPER" && form.safetyItems?.length && !window.confirm("Chuyển sang PCT điện tử sẽ bỏ các mối nguy và biện pháp đã chọn trên phiếu này. Tiếp tục?")) return;
    setForm(prev => ({ ...prev, teamType, format, safetyItems: format === "PAPER" ? prev.safetyItems : [] }));
  }
  function changeKind(kind: PermitKind) {
    if (form.safetyItems?.length && !window.confirm("Đổi loại PCT sẽ bỏ các mối nguy và biện pháp đã chọn để chọn lại đúng danh mục. Tiếp tục?")) return;
    setForm(prev => ({ ...prev, kind, safetyItems: [], disciplines: kind === "MECHANICAL" ? prev.disciplines : [] }));
  }
  const issued = ["ISSUED", "ACTIVE", "PAUSED", "WAITING", "CLOSED"].includes(status);
  const active = ["ACTIVE", "PAUSED", "WAITING", "CLOSED"].includes(status);
  const options = initial ? [initial.status, ...(initial.teamType === "CONTRACTOR" ? CONTRACTOR_PERMIT_TRANSITIONS : PERMIT_TRANSITIONS)[initial.status].filter(s => ["ISSUED", "CANCELLED"].includes(s))] : ["DRAFT", "ISSUED"] as PermitStatus[];
  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (form.teamType === "CONTRACTOR" && status !== "DRAFT" && !form.commanderPersonId) { toast.error("Vui lòng chọn CHTT từ danh sách nhà thầu"); return; }
    if (effectivePermitFormat(form) === "PAPER" && status !== "DRAFT" && form.safetyItems?.some(row => !row.forAuthorization && !row.forExecution)) { toast.error("Vui lòng phân công đơn vị thực hiện cho từng biện pháp đã chọn"); return; }
    try { await save.mutateAsync({ id: initial?.id, body: { ...form, ...(form.teamType === "CONTRACTOR" ? { issuerName: issuerDisplay } : {}), status, version: initial?.version } }); toast.success(initial ? "Đã cập nhật sổ PCT" : "Đã ghi phiếu vào sổ"); onClose(); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Không thể lưu phiếu"); }
  }
  return <Dialog open onOpenChange={v => { if (!v && !save.isPending) onClose(); }}><DialogContent className="max-w-4xl"><DialogTitle>{initial ? `Cập nhật PCT ${formatPermitNumber(initial)}` : "Ghi cấp phiếu công tác"}</DialogTitle><DialogDescription>Nhập theo phiếu thực tế. Dấu * là bắt buộc theo trạng thái. Phiếu đã đóng hoặc hủy sẽ khóa chỉnh sửa.</DialogDescription><div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><PermitFormat permit={form} /><span>Hình thức cấp phiếu được chọn riêng với loại đơn vị.</span></div>
    <form onSubmit={submit} className="space-y-5"><fieldset disabled={save.isPending} className="space-y-5"><datalist id={namesId}>{users.data?.data.map(u => <option key={u.id} value={u.name} />)}</datalist>
        <div className="grid gap-4 rounded-xl border border-border p-4 md:grid-cols-2"><label className="block space-y-1.5 text-sm"><span className="font-medium">Loại đơn vị *</span><select className={control} value={form.teamType} onChange={e => { const teamType = e.target.value as PermitInput["teamType"]; changeFormat(defaultPermitFormat(teamType), teamType); }}><option value="INTERNAL">Đơn vị nội bộ</option><option value="CONTRACTOR">Đơn vị ngoài / Nhà thầu</option></select></label>
          <label className="block space-y-1.5 text-sm"><span className="font-medium">Hình thức cấp phiếu *</span><select className={control} value={effectivePermitFormat(form)} onChange={e => changeFormat(e.target.value as PermitFormatValue)}>{Object.entries(PERMIT_FORMATS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><p className="text-xs text-muted-foreground">Mặc định nhà thầu dùng phiếu giấy, nội bộ dùng phiếu điện tử. Có thể chọn phiếu giấy khi hệ thống cấp phiếu điện tử gặp lỗi.</p></label>
        </div>
      <div className="grid items-end gap-3 rounded-lg border border-sky-200 bg-sky-50 p-3 text-sm text-sky-950 md:grid-cols-[minmax(0,1fr)_auto]"><label className="space-y-1.5"><span className="font-medium">Cương vị</span><select className={control} value={form.position} onChange={e => set("position", e.target.value)}><option value="">Tất cả cương vị</option>{OPERATION_POSITION_TITLES.map(value => <option key={value} value={value}>{value}</option>)}</select><p className="text-xs">Không bắt buộc. Cương vị đã chọn được ưu tiên khi mở danh sách SYC.</p></label><Button type="button" variant="outline" size="sm" onClick={() => setPickSyc(true)}>Chọn SYC sửa chữa</Button></div>
      <label className="block space-y-1.5 text-sm"><span className="font-medium">Phân loại công việc (KH/ĐX/SC)</span><select className={control} value={form.workType ?? ""} onChange={e => set("workType", (e.target.value || null) as PermitWorkType | null)}><option value="">Để trống / Chưa phân loại</option>{Object.entries(PERMIT_WORK_TYPES).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select><p className="text-xs text-muted-foreground">Không bắt buộc. Có thể để trống hoặc ghi KH, ĐX hay SC theo sổ giấy.</p></label>
      <div className="grid gap-4 md:grid-cols-3"><label className="space-y-1.5 text-sm"><span className="font-medium">Loại PCT *</span><select className={control} value={form.kind} disabled={!numberEditable} onChange={e => changeKind(e.target.value as PermitKind)}>{Object.entries(PERMIT_KINDS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><div className="space-y-1.5 text-sm"><label className="block space-y-1.5"><span className="font-medium">Số PCT *</span><input className={control} required maxLength={80} value={form.number} disabled={!numberEditable} onChange={e => set("number", e.target.value)} /></label><p className="break-words text-xs text-muted-foreground">{form.number.trim() ? `Số đầy đủ: ${formatPermitNumber(form)}` : "Chỉ cần nhập số; hệ thống tự ghép năm và /VH1-NĐDH."}</p>{numberEditable && <div className="flex min-h-8 flex-wrap items-center gap-x-2 gap-y-1 rounded-lg bg-sky-50 px-2.5 py-2 text-xs text-sky-950" aria-live="polite">{numberSuggestion.isPending ? <span>Đang tìm số cao nhất trong năm…</span> : numberSuggestion.isError ? <span>Chưa lấy được gợi ý số PCT.</span> : <><span>Số cao nhất năm {form.year}: <strong className="tabular-nums">{numberSuggestion.data?.data.highest ?? "chưa có"}</strong></span>{numberSuggestion.data?.data.suggested && <Button type="button" variant="ghost" size="sm" className="h-7 px-2 text-xs text-blue-700 hover:text-blue-800" onClick={() => set("number", numberSuggestion.data!.data.suggested!)}>Điền số {numberSuggestion.data.data.suggested}</Button>}</>}</div>}</div><label className="space-y-1.5 text-sm"><span className="font-medium">Năm cấp số *</span><input className={control} type="number" min={2000} max={2100} required value={form.year} disabled={!numberEditable} onChange={e => set("year", Number(e.target.value))} /><p className="text-xs text-muted-foreground">Dãy số được tính riêng cho sổ {PERMIT_KINDS[form.kind]} và bắt đầu lại theo từng năm.</p></label></div>
      <div className="grid gap-4 md:grid-cols-2"><label className="space-y-1.5 text-sm"><span className="font-medium">Tổ máy *</span><select className={control} value={form.unit} onChange={e => set("unit", e.target.value as PermitInput["unit"])}>{Object.entries(PERMIT_UNITS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label className="space-y-1.5 text-sm"><span className="font-medium">Ngày thực hiện *</span><input className={control} required type="date" value={form.workDate} onChange={e => set("workDate", e.target.value)} /></label>{!(effectivePermitFormat(form) === "PAPER" && form.kind === "MECHANICAL") && textField("location")}{textField("repairRequestNumber")}
      <label className="space-y-1.5 text-sm md:col-span-2"><span className="font-medium">Nội dung công việc *</span><textarea className={control} rows={3} maxLength={5000} required value={form.content} onChange={e => set("content", e.target.value)} /></label></div>
      {effectivePermitFormat(form) === "PAPER" && <section className="space-y-4 rounded-xl border border-border p-4"><h3 className="font-semibold">Thông tin điền mẫu PCT giấy</h3>
        {form.kind === "MECHANICAL" && <label className="block space-y-1.5 text-sm"><span className="font-medium">Địa điểm công tác (Mục A)</span><input className={control} value={form.location} maxLength={500} onChange={e => set("location", e.target.value)} placeholder="Địa điểm thực hiện công việc ghi tại mục A của PCT Cơ" /><p className="text-xs text-muted-foreground">Nếu chọn SYC, hệ thống sẽ gợi ý địa điểm theo thiết bị; có thể chỉnh lại trước khi lưu phiếu.</p></label>}
        <label className="block space-y-1.5 text-sm"><span className="font-medium">Số ĐKCT</span><input className={control} maxLength={200} value={form.registrationNumber ?? ""} onChange={e => set("registrationNumber", e.target.value)} placeholder="Ví dụ: 2609/2026/ĐK-SCCN hoặc điện trực tiếp" /><p className="text-xs text-muted-foreground">Số giấy đăng ký công tác của đơn vị công tác, khác số SYC sửa chữa. Không bắt buộc; để trống thì không ghi trên mẫu in.</p></label>
        {form.kind === "MECHANICAL" && <label className="block space-y-1.5 text-sm"><span className="font-medium">Phạm vi công tác</span><textarea className={control} rows={2} maxLength={5000} value={form.workScope ?? ""} onChange={e => set("workScope", e.target.value)} placeholder="Giới hạn thiết bị, khu vực được phép thực hiện công việc" /></label>}
        <div className="grid gap-4 md:grid-cols-2">{(["plannedStartAt", "plannedEndAt"] as const).map(key => <label key={key} className="space-y-1.5 text-sm"><span className="font-medium">{PERMIT_FIELD_LABELS[key]} (giờ Việt Nam)</span><input className={control} type="datetime-local" value={localTime(form[key] ?? null)} min={key === "plannedEndAt" ? localTime(form.plannedStartAt ?? null) || undefined : undefined} onChange={e => set(key, e.target.value ? `${e.target.value}:00+07:00` : null)} /></label>)}</div>
        <p className="text-xs text-muted-foreground">Thời gian dự kiến ghi trên phiếu, độc lập với thời gian mở/kết thúc các lần làm việc thực tế. Có thể bổ sung sau.</p>
        {form.kind === "MECHANICAL" && <fieldset className="rounded-lg border border-border p-3"><legend className="px-1 text-sm font-medium">Chuyên môn</legend><div className="flex flex-wrap gap-5">{Object.entries(PERMIT_DISCIPLINES).map(([key, label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" className="h-4 w-4 accent-blue-700" checked={(form.disciplines ?? []).includes(key as PermitDiscipline)} onChange={e => set("disciplines", e.target.checked ? [...(form.disciplines ?? []), key as PermitDiscipline] : (form.disciplines ?? []).filter(v => v !== key))} />{label}</label>)}</div><p className="mt-2 text-xs text-muted-foreground">Đánh dấu các chuyên môn phù hợp để điền đúng ô trên mẫu Cơ – Nhiệt – Hóa.</p></fieldset>}
      </section>}
      {effectivePermitFormat(form) === "PAPER" && form.kind === "MECHANICAL" && <PermitSafetySelection key={form.kind} kind={form.kind} value={form.safetyItems ?? []} onChange={value => set("safetyItems", value)} />}
      <div className="rounded-xl border border-border p-4"><h3 className="mb-3 font-semibold">Nhân sự và đơn vị công tác</h3>
<div className="grid gap-4 md:grid-cols-2">{form.teamType === "CONTRACTOR" ? <label className="space-y-1.5 text-sm"><span className="font-medium">Người cấp PCT</span><input className={`${control} bg-muted/50`} readOnly value={issuerDisplay} placeholder="Đang lấy tài khoản…" /><p className="text-xs text-muted-foreground">{initial && initial.status !== "DRAFT" ? "Giữ người đã cấp phiếu; người cập nhật được ghi riêng trong lịch sử." : "Tự ghi theo tài khoản thao tác khi cấp phiếu."}</p></label> : textField("issuerName", issued)}{form.teamType !== "CONTRACTOR" && textField("leaderName")}{form.teamType === "CONTRACTOR" ? <div className="space-y-1.5 text-sm"><span className="font-medium">Chỉ huy trực tiếp{issued ? " *" : ""}</span><div className="rounded-lg border border-input p-3"><p className="mb-2 font-medium">{form.commanderName || "Chưa chọn CHTT"}</p><Button type="button" variant="outline" size="sm" onClick={() => setPickCommander(true)}>{form.commanderPersonId ? "Đổi CHTT" : "Chọn CHTT nhà thầu"}</Button></div><p className="text-xs text-muted-foreground">Chọn từ danh sách đã được cung cấp. CHTT chỉ được giữ khi mở lần làm việc.</p></div> : textField("commanderName", issued)}{textField("teamName", issued)}{form.teamType === "CONTRACTOR" ? <p className="text-sm text-muted-foreground">CHTT đã được tính là người công tác. Nhân viên bổ sung không bắt buộc.</p> : <label className="space-y-1.5 text-sm"><span className="font-medium">Số nhân viên{issued ? " *" : ""}</span><input className={control} type="number" min={1} max={10000} step={1} required={issued} readOnly={form.members.length > 0} value={form.members.length || form.workerCount || ""} onChange={e => set("workerCount", e.target.value ? Number(e.target.value) : null)} /></label>}{form.kind === "ELECTRICAL" && effectivePermitFormat(form) === "PAPER" && textField("electricalSafetySupervisorName")}{form.teamType !== "CONTRACTOR" && <div className="space-y-1.5 text-sm"><span className="font-medium">Người cho phép làm việc</span><p className="rounded-lg border border-border p-3 text-muted-foreground">{form.authorizerName || "Ghi nhận trong Thực hiện phiếu"}</p></div>}</div></div>
      {form.teamType === "CONTRACTOR" && <details className="rounded-xl border border-border p-4"><summary className="cursor-pointer text-sm font-medium">Thông tin bổ sung: lãnh đạo và nhân viên công tác</summary><div className="mt-4 space-y-4">{textField("leaderName")}<PermitMembersEditor members={form.members} onChange={value => set("members", value)} commander={form.commanderPersonId ? { personId: form.commanderPersonId, name: form.commanderName, code: "", company: form.teamName } : undefined} /></div></details>}
      {form.teamType === "CONTRACTOR" && <p className="rounded-lg bg-sky-50 p-3 text-sm text-sky-950">Sau khi cấp phiếu, vào chi tiết để mở/kết thúc từng lần làm việc. Mỗi lần chọn CHTT nhà thầu từ danh sách và ghi thời gian thực tế.</p>}
      <div className="rounded-xl border border-border p-4"><h3 className="mb-3 font-semibold">Tiến độ và kết quả</h3><div className="grid gap-4 md:grid-cols-2"><label className="space-y-1.5 text-sm"><span className="font-medium">Trạng thái ghi nhận *</span><select className={control} value={status} onChange={e => { const next = e.target.value as PermitStatus; setStatus(next); setForm(prev => ({ ...prev, issuedAt: next === "DRAFT" ? null : prev.issuedAt ?? (next === "ISSUED" ? `${vietnamNow()}:00+07:00` : null), authorizedAt: ["DRAFT", "ISSUED"].includes(next) ? null : prev.authorizedAt, closedAt: next === "CLOSED" ? prev.closedAt : null })); }}>{options.map(v => <option key={v} value={v}>{PERMIT_STATUSES[v]}</option>)}</select><p className="text-xs text-muted-foreground">{status === "DRAFT" ? "Nháp là lưu tạm, chưa ghi nhận cấp phiếu và chưa giữ CHTT. Chọn Đã cấp nếu phiếu đã được cấp thực tế." : status === "ISSUED" ? "Ghi nhận phiếu đã cấp thực tế. Với nhà thầu, CHTT chỉ được giữ khi mở lần làm việc." : "Ghi theo tình trạng thực tế của phiếu."}</p></label>{status !== "DRAFT" && dateField("issuedAt", issued)}{active && form.teamType !== "CONTRACTOR" && dateField("authorizedAt", true)}{status === "CLOSED" && dateField("closedAt", true)}
      {["PAUSED", "CANCELLED"].includes(status) && <label className="space-y-1.5 text-sm md:col-span-2"><span className="font-medium">Lý do {status === "PAUSED" ? "tạm dừng" : "hủy phiếu"} *</span><textarea className={control} rows={2} disabled={status === "PAUSED"} required maxLength={2000} value={form.statusReason} onChange={e => set("statusReason", e.target.value)} /></label>}
      <label className="space-y-1.5 text-sm md:col-span-2"><span className="font-medium">Kết quả công việc{status === "CLOSED" ? " *" : ""}</span><textarea className={control} rows={2} maxLength={5000} disabled required={status === "CLOSED"} value={form.result} onChange={e => set("result", e.target.value)} /></label><label className="space-y-1.5 text-sm md:col-span-2"><span className="font-medium">Ghi chú</span><textarea className={control} rows={2} maxLength={5000} value={form.note} onChange={e => set("note", e.target.value)} /></label></div></div>
      {["CLOSED", "CANCELLED"].includes(status) && <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Lưu phiếu ở trạng thái {PERMIT_STATUSES[status].toLowerCase()} sẽ khóa chỉnh sửa và giữ số phiếu trong sổ.</p>}
      <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Để sau</Button><Button type="submit" disabled={save.isPending}>{save.isPending ? "Đang lưu…" : `Lưu · ${PERMIT_STATUSES[status]}`}</Button></div>
    </fieldset></form>
    {pickCommander && <PermitPeopleDirectory commandersOnly onClose={() => setPickCommander(false)} onPick={person => { setForm(prev => ({ ...prev, commanderPersonId: person.id, commanderName: person.name, teamName: person.company, members: prev.members.filter(member => member.personId ? member.personId !== person.id : member.code !== person.code) })); setPickCommander(false); }} />}
    {pickSyc && <SycPicker kind={form.kind} position={form.position} onClose={() => setPickSyc(false)} onPick={d => { setForm(prev => ({ ...prev, repairRequestNumber: d.requestNumber ?? "", content: d.content ?? prev.content, location: [d.deviceSeq, d.node?.name || d.sourceDeviceRaw || d.device].filter(Boolean).join(" · "), unit: Object.hasOwn(PERMIT_UNITS, d.unit) ? d.unit as PermitInput["unit"] : prev.unit })); setPickSyc(false); }} />}
  </DialogContent></Dialog>;
}
function SycPicker({ kind, position, onClose, onPick }: { kind: PermitKind; position: string; onClose: () => void; onPick: (d: DefectItem) => void }) {
  const [q, setQ] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  useEffect(() => { const t = setTimeout(() => { setSearch(q); setPage(1); }, 300); return () => clearTimeout(t); }, [q]);
  const list = useDefects({ section: kind === "MECHANICAL" ? "co" : "dien", q: search, priorityPosition: position, page, limit: 10 });
  return <Dialog open onOpenChange={v => { if (!v) onClose(); }}><DialogContent className="max-w-2xl"><DialogTitle>Chọn SYC sửa chữa</DialogTitle><DialogDescription>{position ? `Ưu tiên SYC của cương vị ${position}. Tìm kiếm vẫn trả cả SYC thuộc cương vị khác.` : "Đang hiển thị SYC của tất cả cương vị."} Thông tin được sao chép vào sổ PCT để đối chiếu.</DialogDescription><input aria-label="Tìm SYC" className={control} placeholder="Tìm số SYC, nội dung, thiết bị, cương vị…" value={q} onChange={e => setQ(e.target.value)} />{list.isError ? <p role="alert">{list.error.message}</p> : list.isPending ? <p>Đang tải SYC…</p> : <div className="space-y-2">{list.data?.data.map(d => { const preferred = Boolean(position && announcementPositionsMatch(d.system, position)); return <button disabled={!d.requestNumber || list.isFetching} className={`w-full rounded-lg border p-3 text-left hover:bg-muted disabled:opacity-50 ${preferred ? "border-blue-300 bg-blue-50/60" : "border-border"}`} key={d.id} onClick={() => onPick(d)}><div className="flex flex-wrap items-center justify-between gap-2"><b>{d.requestNumber || "Chưa cấp số"} · {d.unit}</b>{preferred && <span className="rounded-full bg-blue-100 px-2 py-0.5 text-xs font-semibold text-blue-800">Đúng cương vị ưu tiên</span>}</div><p className="line-clamp-2 text-sm">{d.content || "Chưa có nội dung"}</p><p className="text-xs text-muted-foreground">{d.system || "Chưa ghi cương vị"} · {d.deviceSeq} · {d.node?.name || d.sourceDeviceRaw || d.device}</p></button>; })}{!list.data?.data.length && <p className="p-4 text-center">Không tìm thấy SYC phù hợp.</p>}</div>}<div className="flex justify-end gap-2"><Button variant="outline" disabled={page <= 1 || list.isFetching} onClick={() => setPage(page - 1)}>Trước</Button><Button variant="outline" disabled={!list.data || page >= list.data.meta.totalPages || list.isFetching} onClick={() => setPage(page + 1)}>Sau</Button></div></DialogContent></Dialog>;
}
function PermitDetail({ id, canIssue: listCanIssue, canExecute: listCanExecute, onClose, onEdit }: { id: string; canIssue: boolean; canExecute: boolean; onClose: () => void; onEdit: (r: PermitRow) => void }) {
  const query = useWorkPermit(id);
  const [executing, setExecuting] = useState(false); const row = query.data?.data;
  const canIssue = query.data?.meta?.canIssue ?? listCanIssue;
  const canExecute = query.data?.meta?.canExecute ?? listCanExecute;
  const documentExport = useExportPermitTemplate();
  async function downloadTemplate() {
    try {
      const file = await documentExport.mutateAsync(id), url = URL.createObjectURL(file.blob);
      const a = document.createElement("a"); a.href = url; a.download = file.filename; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (e) { toast.error(e instanceof Error ? e.message : "Không thể tải mẫu phiếu"); }
  }
  return <Dialog open onOpenChange={v => { if (!v) onClose(); }}><DialogContent className="max-w-3xl"><DialogTitle>{row ? `Phiếu công tác ${formatPermitNumber(row)}` : "Chi tiết phiếu công tác"}</DialogTitle><DialogDescription>Thông tin ghi sổ và lịch sử thay đổi của phiếu.</DialogDescription>{query.isError ? <p role="alert">{query.error.message}</p> : !row ? <p>Đang tải phiếu…</p> : <><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><Status value={row.status} /><PermitFormat permit={row} /></div><PermitProgress value={row.progress} /></div>{canIssue && !["CLOSED", "CANCELLED"].includes(row.status) && !(row.teamType === "CONTRACTOR" && row.status === "ACTIVE") && <Button onClick={() => onEdit(row)}>Chỉnh sửa / cấp phiếu<ArrowRight /></Button>}</div><ContractorSessions key={`${row.id}-${row.version}`} permit={row} canExecute={canExecute} />{canExecute && !["DRAFT", "CLOSED", "CANCELLED"].includes(row.status) && <Button variant="outline" onClick={() => setExecuting(true)}>Thực hiện / cập nhật tiến độ</Button>}{executing && canExecute && <PermitExecutionDialog key={row.version} permit={row} onClose={() => setExecuting(false)} />}<dl className="grid gap-4 rounded-xl border border-border p-4 sm:grid-cols-2">{Object.entries(PERMIT_FIELD_LABELS).filter(([key]) => !["status", "number", "year", "safetyItems"].includes(key)).map(([key, label]) => <div key={key} className={["content", "result", "note", "statusReason", "workScope"].includes(key) ? "sm:col-span-2" : ""}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm font-medium">{permitValue(key, key === "format" ? effectivePermitFormat(row) : row[key as keyof PermitRow])}</dd></div>)}</dl>{effectivePermitFormat(row) === "PAPER" && <><PermitSafetyReadOnly value={row.safetyItems ?? []} /><Button variant="outline" disabled={documentExport.isPending || ["DRAFT", "CANCELLED"].includes(row.status)} onClick={downloadTemplate}><Download />{documentExport.isPending ? "Đang điền mẫu…" : "Tải mẫu PCT giấy (Word)"}</Button><p className="text-xs text-muted-foreground">Mẫu điền theo thông tin đã lưu và phân công biện pháp. Các ô kiểm tra, chữ ký và thông tin chưa ghi được để trống để hoàn thiện.</p></>}<PermitHistoryPanel key={`${row.id}-${row.version}`} permit={row} /></>}</DialogContent></Dialog>;
}
