import { adaptTcmsRoute } from "@/lib/tcms/server/http/route-adapter";
import {permissionsForRoles} from "@/lib/tcms/lib/security/authorization";import {requireContractPermission,requireRolePermission} from "@/lib/tcms/server/contracts/contract-api";import {PostgresContractRepository} from "@/lib/tcms/server/contracts/postgres-contract-repository";import {withSecurityTransaction} from "@/lib/tcms/server/db/security-transaction";import {apiError} from "@/lib/tcms/server/http/api-response";import {getRequestContext} from "@/lib/tcms/server/http/request-context";import {parseAcceptanceInput} from "@/lib/tcms/server/acceptance/acceptance-service";import {PostgresAcceptanceRepository} from "@/lib/tcms/server/acceptance/postgres-acceptance-repository";
async function GETHandler(request:Request){try{const context=await getRequestContext(request);requireRolePermission(context.principal,"contract.read");const canManage=permissionsForRoles(context.principal.roles).has("contract.acceptance.update");const result=await withSecurityTransaction(context,async(client)=>{const repository=new PostgresAcceptanceRepository(client);return {acceptances:await repository.list(),summary:await repository.summary(),options:await repository.options(canManage)};});return Response.json({...result,capabilities:{canManage}},{headers:{"cache-control":"no-store"}});}catch(error){return apiError(error);}}
async function POSTHandler(request:Request){try{const context=await getRequestContext(request);const input=parseAcceptanceInput(await request.json());const acceptance=await withSecurityTransaction(context,async(client)=>{const contract=await new PostgresContractRepository(client).findById(input.contractId);if(!contract)throw new Error("ACCEPTANCE_CONTRACT_NOT_FOUND");requireContractPermission(context.principal,"contract.acceptance.update",contract);return new PostgresAcceptanceRepository(client).create(input,context.principal.userId);});return Response.json({acceptance},{status:201,headers:{"cache-control":"no-store"}});}catch(error){return apiError(error);}}

export const dynamic = "force-dynamic";

export const GET = adaptTcmsRoute(GETHandler);

export const POST = adaptTcmsRoute(POSTHandler);
